name: VulnAlerts

on:
  push:
    branches:
      - main

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: y-mehta/vulnalerts@v1.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: done
        run: echo 'done'
